# Generated by Django 3.1.7 on 2021-06-17 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgrooms', '0002_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='statename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgrooms.state'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgname', models.CharField(max_length=100)),
                ('pgtype', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='pics')),
                ('pgaddress', models.TextField()),
                ('gmap', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('bedno', models.IntegerField()),
                ('verifystatus', models.BooleanField(default=False)),
                ('activestatus', models.BooleanField(default=True)),
                ('availbalebed', models.IntegerField()),
                ('freebed', models.IntegerField()),
                ('cityname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgrooms.city')),
                ('statename', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgrooms.state')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
