# Generated by Django 3.1.7 on 2021-07-21 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgrooms', '0005_pgverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktime', models.DateTimeField()),
                ('vacate', models.DateTimeField(blank=True, default=None, null=True)),
                ('payment', models.IntegerField(blank=True, default=None, null=True)),
                ('paymentstatus', models.BooleanField(default=False)),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgrooms.room')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
