# Generated by Django 3.1.7 on 2021-07-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgrooms', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingstatus',
            field=models.BooleanField(default=False),
        ),
    ]
