# Generated by Django 3.1.7 on 2021-07-23 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgrooms', '0007_booking_bookingstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancelledbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canceltime', models.DateTimeField()),
                ('refund', models.IntegerField(blank=True, default=None, null=True)),
                ('refundstatus', models.BooleanField(default=False)),
                ('cancelstatus', models.BooleanField(default=False)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgrooms.booking')),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pgrooms.room')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
