# Generated by Django 3.1.7 on 2021-07-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgrooms', '0009_room_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledbooking',
            name='forcecancel',
            field=models.BooleanField(default=False),
        ),
    ]
