# Generated by Django 3.1.7 on 2021-07-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgrooms', '0010_cancelledbooking_forcecancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='forcecancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refundstatus',
            field=models.BooleanField(default=False),
        ),
    ]
