# Generated by Django 3.1.7 on 2021-07-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgrooms', '0011_auto_20210726_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancelstatus',
            field=models.BooleanField(default=True),
        ),
    ]
