# Generated by Django 3.1.7 on 2021-07-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgrooms', '0012_auto_20210726_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancelstatus',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='forcecancel',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='refundstatus',
        ),
    ]
