# Generated by Django 3.1.7 on 2021-07-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgrooms', '0014_auto_20210726_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledbooking',
            name='canceltime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
