# Generated by Django 3.1.7 on 2021-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgrooms', '0015_auto_20210727_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Booking Report',
                'verbose_name_plural': 'Bookings Report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pgrooms.booking',),
        ),
        migrations.CreateModel(
            name='PGSummary',
            fields=[
            ],
            options={
                'verbose_name': 'PG Summary',
                'verbose_name_plural': 'PGs Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pgrooms.room',),
        ),
        migrations.AddField(
            model_name='room',
            name='cityname1',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='statename1',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
